---
device: 5
dataset: cora  # ['cora', 'citeseer', 'pubmed', 'computers', 'photo', 'chameleon', 'squirrel', 'actor', 'texas', 'cornell']
train_rate: 0.6
val_rate: 0.2

data_process:
  laplacian_type: L3 
  add_self_loop: False


model:
  name: ARMA
  stack_num: 3
  stack_layer_num: 5
  bias: True
  num_layer: 1
  hidden_dim: 32

train:
  epochs: 2000
  early_stopping: 200
  dropout: 0.5
  lr: 0.01
  weight_decay: 0.0005