---
device: 5
dataset: cora  # ['cora', 'citeseer', 'pubmed', 'computers', 'photo', 'chameleon', 'squirrel', 'actor', 'texas', 'cornell']
train_rate: 0.6
val_rate: 0.2

data_process:
  laplacian_type: L2    # L = I - D^{-1/2} A D^{-1/2}

model:
  name: CayleyNet
  k: 10
  num_jacobi_iter: 10
  bias: True
  num_layer: 1
  hidden_dim: 25

train:
  epochs: 2000
  early_stopping: 200
  dropout: 0.6
  dprate: 0.6
  lr: 0.01
  weight_decay: 0.0005

