---
device: 5
dataset: cora  # ['cora', 'citeseer', 'pubmed', 'computers', 'photo', 'chameleon', 'squirrel', 'actor', 'texas', 'cornell']
train_rate: 0.6
val_rate: 0.2

data_process:
  laplacian_type: L2
  need_EVD: True

model:
  name: ChebyNet
  k: 3
  num_layer: 2
  hidden_dim: 32

train:
  epochs: 2000
  early_stopping: 200
  dropout: 0.2
  lr: 0.001
  weight_decay: 0.0005


