---
device: 5
dataset: cora  # ['cora', 'citeseer', 'pubmed', 'computers', 'photo', 'chameleon', 'squirrel', 'actor', 'texas', 'cornell']
train_rate: 0.6
val_rate: 0.2

data_process:
  laplacian_type: L3
  add_self_loop: True

model:
  name: GPRGNN
  k: 15
  alpha: 0.1
  init_method: PPR   #'SGC', 'PPR', 'NPPR', 'Random', 'WS', 'Null'
  num_layer: 1
  hidden_dim: 200

train:
  epochs: 2000
  early_stopping: 200
  dropout: 0.1
  dprate: 0.1
  lr: 0.03
  weight_decay: 0.005